import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/navigation";
import ClientPortal from "./ClientPortal/clientPortal";

const PlusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${PlusJakartaSans.variable} antialiased max-md:w-[90%] max-xl:w-[90%] w-[65%]  mx-auto transition-all`}
      >
        <ClientPortal>
          <Navigation />
        </ClientPortal>

        <main className="mt-50 max-xl:mt-30">{children}</main>
      </body>
    </html>
  );
}
